import 'jquery';
import 'hammerjs';
import 'angular2-materialize';
import 'materializecss';
import 'materialize';
import 'angular2/platform/browser';
import 'angular2/common';
import 'angular2/core';
// import 'angular2/bundles/angular2.dev.js';
import 'angular2/router';
import 'angular2/http';
import 'rxjs';
import 'material-icons';
