---
data:
    build: .
    dockerfile: docker/data/Dockerfile
    command: echo 'Created node development data volume'
    volumes:
       - .:/home/app
       - /home/app/node_modules

app:
    build: .
    dockerfile: docker/app/Dockerfile
    volumes_from:
        - data
    ports:
        - "8080:8080"
    links:
        - mongo:mongo

mongodata:
    build: .
    dockerfile: docker/mongo_data/Dockerfile

mongo:
    image: mongo:3.2.6
    volumes_from:
        - mongodata
    ports:
        - "27017:27017"
    command: --smallfiles --rest --auth
