---
data:
    build: .
    dockerfile: docker/data/Dockerfile
    volumes:
       - .:/home/app

app:
    build: .
    dockerfile: docker/app/dev/Dockerfile
    volumes_from:
        - data
    ports:
        - "8080:8080"
    links:
        - mongo:mongo
        - redis:redis

test:
    build: .
    dockerfile: docker/app/test/Dockerfile
    volumes_from:
        - data

mongodata:
    build: .
    dockerfile: docker/mongo_data/Dockerfile

mongo:
    image: mongo:3.2.6
    volumes_from:
        - mongodata
    ports:
        - "27017:27017"
    command: --smallfiles --rest

redis:
    image: redis:3.2.0-alpine
