version: '2'
services:
    api_data:
        build: 
            context: ./api
            dockerfile: docker/api/data/Dockerfile
        volumes:
           - ./api:/home/api
        networks:
           - front
           - back
    api:
       build:  
           context: ./api
           dockerfile: docker/api/api/Dockerfile
       ports:
           - "3000:3000"
       volumes_from:
           - api_data
       networks:
           - front
           - back

    data:
        build: 
            context: .
            dockerfile: docker/data/Dockerfile
        volumes:
           - .:/home/app
        networks:
           - front

    app:
        build: 
            context: .
            dockerfile: docker/app/dev/Dockerfile
        volumes_from:
            - data
        ports:
            - "8080:8080"
        networks:
            - front

    test:
        build: 
            context: .
            dockerfile: docker/app/test/Dockerfile
        volumes_from:
            - data
        ports:
            - "9876:9876"
        networks:
            - front


    mongodata:
        build: 
            context: .
            dockerfile: docker/mongo_data/Dockerfile
        networks:
            - back

    mongo:
        image: mongo:3.2.6
        volumes_from:
            - mongodata
        ports:
            - "27017:27017"
        command: --smallfiles --rest
        networks:
            - back

    redis:
        image: redis:3.2.0-alpine
        networks:
            - back
networks:
    front:
    back:
