version: '2'
services:
    api_data:
        build: 
            context: ./api
            dockerfile: docker/api/data/Dockerfile
        volumes:
           - .:/home/api
    api:
       build:  
           context: .
           dockerfile: docker/api/api/Dockerfile
       ports:
           - "3000:3000"
       volumes_from:
           - api_data

    data:
        build: 
            context: .
            dockerfile: docker/data/Dockerfile
        volumes:
           - .:/home/app

    app:
        build: 
            context: .
            dockerfile: docker/app/dev/Dockerfile
        volumes_from:
            - data
        ports:
            - "8080:8080"

    test:
        build: 
            context: .
            dockerfile: docker/app/test/Dockerfile
        volumes_from:
            - data
        ports:
            - "9876:9876"
        external_links:
            - api_api:api


    mongodata:
        build: 
            context: .
            dockerfile: docker/mongo_data/Dockerfile

    mongo:
        image: mongo:3.2.6
        volumes_from:
            - mongodata
        ports:
            - "27017:27017"
        command: --smallfiles --rest

    redis:
        image: redis:3.2.0-alpine
